'''SATSolver.py - a simple Python interface to the zchaff SAT solver.
Originally by Todd Neller
Ported to Python by Dave Musicant
Copyright (C) 2008 Dave Musicant
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
Information about the GNU General Public License is available online at:
http://www.gnu.org/licenses/
To receive a copy of the GNU General Public License, write to the Free
Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
02111-1307, USA.
'''

import subprocess
import os


def testKb(clauses,file_name):
    maxVar = 0
    print(os.getcwd())
    for clause in clauses:
        for literal in clause:
            maxVar = max(abs(literal),maxVar)
    print(len(clauses))
    file_loc = 'cnfFiles/' + file_name
    out = open(file_loc,'w')
    out.write('c CNF file was generated by SATSolver.py\n')
    out.write('p cnf ' + str(maxVar) + ' ' + str(len(clauses))+ '\n')
    for clause in clauses:
        for literal in clause:
            out.write(str(literal) + ' ')
        out.write('0\n')
        #     print >> out,literal,
        # print >> out,'0'
    out.close();
    process = subprocess.Popen('/usr/local/bin/zchaff '+ file_loc,stdout=subprocess.PIPE,
                shell=True)
    process.wait()
    stdout = process.stdout
    return stdout.read()
